# Setup
title: presequences - blog
url: "http://presequences.com"
permalink: /:year/:month/:day/:title/

# Google analytics
google_analytics: UA-62182426-2

# Social accounts
github_username: andrewpmiller
twitter_username: andrewpmiller
linkedin_username: andrewpmiller


debug: true

gems:
   - jekyll-mentions
   - jemoji
   - jekyll-sitemap
   - jekyll-feed

# Conversion
markdown: kramdown

kramdown:
    input: GFM

highlighter: rouge



# Serving
# detach:  false
# port:    4000
# host:    127.0.0.1
# baseurl: / # does not include hostname
# show_dir_listing: false

exclude:
  - Gemfile
  - Gemfile.lock
  - docker-compose.yml

repository: andrewpmiller/presequences
github:
  url: http://localhost:4000
